name: Model Architecture Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  model-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision numpy

    - name: Run Model Checks
      run: |
        python .github/scripts/check_model.py

    - name: Upload check results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: check-results
        path: model_check_results.txt 